apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/name: inventory
    app.kubernetes.io/part-of: app-inventory
  name: inventory
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory
      app.kubernetes.io/part-of: app-inventory
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: inventory
        app.kubernetes.io/part-of: app-inventory
    spec:
      containers:
      - image:        "quay.io/globex/inventory:main-1cb658793fee68a670ed9d50ad1913905fd47602"
        imagePullPolicy: Always
        name: inventory
        ports:
        - containerPort: 8080
        resources: {}
        env:
          - name: QUARKUS_DATASOURCE_USERNAME
            value: sa
          - name: QUARKUS_DATASOURCE_PASSWORD
            value: sa
          - name: QUARKUS_DATASOURCE_JDBC_URL
            value: jdbc:postgresql://inventory-database:5432/inventory
      serviceAccountName: default
status: {}
