apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: catalog
    app.kubernetes.io/part-of: app-catalog
    app.openshift.io/runtime: spring
  name: catalog
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog
      app.kubernetes.io/part-of: app-catalog
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: catalog
        app.kubernetes.io/part-of: app-catalog
    spec:
      containers:
      - image:  "quay.io/globex/catalog:main-037c8ba1612f245d9cc8dfd57417ff5328fb0e53"
        imagePullPolicy: Always
        name: catalog
        ports:
        - containerPort: 8080
        env:
          - name: JAVA_OPTIONS
            value: -Dspring.profiles.active=openshift
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://catalog-database:5432/catalog
          - name: SPRING_DATASOURCE_USERNAME
            value: sa
          - name: SPRING_DATASOURCE_PASSWORD
            value: sa
          - name: INVENTORY_URL
            value: inventory:8080
        resources: {}
      serviceAccountName: default
status: {}
